-- Production-safe hardening.
-- This migration does not delete, rewrite, move, or recreate any existing
-- profile, entry, vote, image, or Storage object.
begin;

-- Prevent parent records from silently deleting formal contest data.
do $$
declare
  fk record;
  replacement text;
begin
  for fk in
    select c.oid, c.conname, c.conrelid::regclass as table_name,
      pg_get_constraintdef(c.oid) as definition
    from pg_constraint c
    where c.contype = 'f'
      and c.confdeltype = 'c'
      and c.conrelid in (
        'public.profiles'::regclass,
        'public.entries'::regclass,
        'public.entry_images'::regclass,
        'public.votes'::regclass,
        'public.announcements'::regclass
      )
  loop
    replacement := regexp_replace(fk.definition, 'ON DELETE CASCADE', 'ON DELETE RESTRICT', 'i');
    execute format('alter table %s drop constraint %I', fk.table_name, fk.conname);
    execute format('alter table %s add constraint %I %s', fk.table_name, fk.conname, replacement);
  end loop;
end
$$;

-- Append-only history enables deterministic "first reached this vote total"
-- tie-breaking without changing the canonical votes table.
create table if not exists public.vote_history (
  id bigint generated by default as identity primary key,
  vote_id bigint not null,
  event_id uuid not null references public.events(id) on delete restrict,
  entry_id bigint not null references public.entries(id) on delete restrict,
  voter_id uuid not null references public.profiles(id) on delete restrict,
  action text not null check (action in ('added', 'removed')),
  occurred_at timestamptz not null default now(),
  unique (vote_id, action, occurred_at)
);

create index if not exists vote_history_entry_time_idx
  on public.vote_history (event_id, entry_id, occurred_at, id);

alter table public.vote_history enable row level security;

create or replace function public.record_vote_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.vote_history (
    vote_id, event_id, entry_id, voter_id, action, occurred_at
  ) values (
    case when tg_op = 'DELETE' then old.id else new.id end,
    case when tg_op = 'DELETE' then old.event_id else new.event_id end,
    case when tg_op = 'DELETE' then old.entry_id else new.entry_id end,
    case when tg_op = 'DELETE' then old.voter_id else new.voter_id end,
    case when tg_op = 'DELETE' then 'removed' else 'added' end,
    case when tg_op = 'DELETE' then now() else new.created_at end
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists record_vote_history_trigger on public.votes;
create trigger record_vote_history_trigger
after insert or delete on public.votes
for each row execute function public.record_vote_history();

insert into public.vote_history (
  vote_id, event_id, entry_id, voter_id, action, occurred_at
)
select v.id, v.event_id, v.entry_id, v.voter_id, 'added', v.created_at
from public.votes v
where not exists (
  select 1
  from public.vote_history h
  where h.vote_id = v.id and h.action = 'added'
);

-- Explicit lock/closed overrides always win, including when status is
-- explicitly voting_open.
drop policy if exists "own vote creation" on public.votes;
create policy "own vote creation" on public.votes
for insert
with check (
  votes.voter_id = (select auth.uid())
  and exists (
    select 1
    from public.entries en
    join public.events ev on ev.id = en.event_id
    join public.profiles p on p.id = (select auth.uid())
    where en.id = votes.entry_id
      and en.event_id = votes.event_id
      and en.status = 'approved'
      and en.withdrawn_at is null
      and not p.is_disqualified
      and not ev.voting_locked
      and ev.voting_override <> 'closed'
      and (
        ev.status = 'voting_open'
        or (
          ev.status is null
          and (
            ev.voting_override = 'open'
            or (
              ev.voting_override = 'auto'
              and now() between ev.voting_starts_at and ev.voting_ends_at
            )
          )
        )
      )
  )
);

drop policy if exists "own vote cancellation" on public.votes;
create policy "own vote cancellation" on public.votes
for delete
using (
  votes.voter_id = (select auth.uid())
  and exists (
    select 1
    from public.events ev
    where ev.id = votes.event_id
      and not ev.voting_locked
      and ev.voting_override <> 'closed'
      and (
        ev.status = 'voting_open'
        or (
          ev.status is null
          and (
            ev.voting_override = 'open'
            or (
              ev.voting_override = 'auto'
              and now() between ev.voting_starts_at and ev.voting_ends_at
            )
          )
        )
      )
  )
);

-- The bucket is public, so object URLs remain viewable without granting users
-- permission to enumerate every Storage row.
drop policy if exists "public entry images" on storage.objects;

-- Browser roles must never receive destructive table-level privileges or direct access to
-- server-managed records. RLS remains enabled as a second layer.
revoke all on table
  public.admin_roles,
  public.awards,
  public.award_assignments,
  public.award_rules,
  public.award_exclusions,
  public.audit_logs,
  public.audit_cleanup_runs,
  public.activity_snapshots,
  public.idempotency_keys,
  public.vote_history
from anon, authenticated;

grant select, insert, update, delete on table
  public.admin_roles,
  public.awards,
  public.award_assignments,
  public.award_rules,
  public.award_exclusions,
  public.audit_logs,
  public.audit_cleanup_runs,
  public.activity_snapshots,
  public.idempotency_keys,
  public.vote_history
to service_role;

grant usage, select on sequence public.vote_history_id_seq to service_role;

revoke execute on function public.record_vote_history() from public, anon, authenticated;

commit;
