-- Extends scoped correction grants with append-only image additions and
-- original-image revisions. Existing entries, votes, entry_images rows, and
-- Storage objects are not updated, deleted, moved, or overwritten.
begin;

alter table public.submission_edit_grants
  add column if not exists allow_add_images boolean not null default false;

alter table public.submission_edit_grants
  add column if not exists allow_replace_original boolean not null default false;

alter table public.submission_edit_grants
  add column if not exists allow_reorder_images boolean not null default false;

alter table public.submission_edit_grants
  add column if not exists allow_remove_images boolean not null default false;

alter table public.submission_edit_grants
  add column if not exists allowed_image_ids bigint[] not null default array[]::bigint[];

create table if not exists public.entry_original_image_revisions (
  id bigint generated by default as identity primary key,
  entry_id bigint references public.entries(id) on delete set null,
  grant_id uuid references public.submission_edit_grants(id) on delete set null,
  storage_object_path text not null,
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  superseded_at timestamptz
);

create unique index if not exists entry_original_image_revisions_one_active_idx
  on public.entry_original_image_revisions(entry_id)
  where is_active = true;

create index if not exists entry_original_image_revisions_entry_created_idx
  on public.entry_original_image_revisions(entry_id, created_at desc);

create index if not exists entry_original_image_revisions_grant_idx
  on public.entry_original_image_revisions(grant_id)
  where grant_id is not null;

create index if not exists entry_original_image_revisions_created_by_idx
  on public.entry_original_image_revisions(created_by)
  where created_by is not null;

alter table public.entry_original_image_revisions enable row level security;
revoke all on table public.entry_original_image_revisions from anon, authenticated;
grant all on table public.entry_original_image_revisions to service_role;
grant usage, select on sequence public.entry_original_image_revisions_id_seq to service_role;

create table if not exists public.entry_image_display_settings (
  id bigint generated by default as identity primary key,
  image_id bigint unique references public.entry_images(id) on delete set null,
  entry_id bigint references public.entries(id) on delete set null,
  display_position smallint not null,
  is_hidden boolean not null default false,
  grant_id uuid references public.submission_edit_grants(id) on delete set null,
  updated_by uuid references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint entry_image_display_settings_position_check
    check (display_position between 1 and 999)
);

create index if not exists entry_image_display_settings_entry_idx
  on public.entry_image_display_settings(entry_id, display_position);

create index if not exists entry_image_display_settings_grant_idx
  on public.entry_image_display_settings(grant_id)
  where grant_id is not null;

create index if not exists entry_image_display_settings_updated_by_idx
  on public.entry_image_display_settings(updated_by)
  where updated_by is not null;

alter table public.entry_image_display_settings enable row level security;
revoke all on table public.entry_image_display_settings from anon, authenticated;
grant all on table public.entry_image_display_settings to service_role;
grant usage, select on sequence public.entry_image_display_settings_id_seq to service_role;

-- Keep uploads insert-only. Replacement and addition files always use new
-- object names; browser roles do not receive UPDATE, DELETE, MOVE, or UPSERT.
drop policy if exists "authorized correction entry uploads" on storage.objects;
create policy "authorized correction entry uploads"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'cos-entries'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and lower(storage.extension(name)) = any (array['jpg', 'jpeg', 'png', 'webp'])
  and exists (
    select 1
    from public.submission_edit_grants grant_row
    join public.entries entry_row on entry_row.id = grant_row.entry_id
    where grant_row.grantee_profile_id = (select auth.uid())
      and entry_row.owner_id = (select auth.uid())
      and grant_row.is_active = true
      and grant_row.revoked_at is null
      and grant_row.expires_at > now()
      and (
        storage.filename(name) like '%-correction-entry-%'
        or (
          storage.filename(name) like '%-correction-add-%'
          and grant_row.allow_add_images = true
        )
      )
  )
);

drop policy if exists "authorized correction original uploads" on storage.objects;
create policy "authorized correction original uploads"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'cos-originals'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and lower(storage.extension(name)) = any (array['jpg', 'jpeg', 'png', 'webp'])
  and storage.filename(name) like '%-correction-original-%'
  and exists (
    select 1
    from public.submission_edit_grants grant_row
    join public.entries entry_row on entry_row.id = grant_row.entry_id
    where grant_row.grantee_profile_id = (select auth.uid())
      and entry_row.owner_id = (select auth.uid())
      and grant_row.is_active = true
      and grant_row.revoked_at is null
      and grant_row.expires_at > now()
      and grant_row.allow_replace_original = true
  )
);

-- Applies all media changes atomically after the server has verified the
-- authenticated owner, exact grant, Storage objects, and input values.
create or replace function public.apply_submission_media_corrections(
  target_entry_id bigint,
  target_grantee_profile_id uuid,
  target_grant_id uuid,
  replacements jsonb default '[]'::jsonb,
  additions jsonb default '[]'::jsonb,
  image_states jsonb default '[]'::jsonb,
  new_original_storage_path text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  grant_row public.submission_edit_grants%rowtype;
  replacement jsonb;
  addition jsonb;
  image_state jsonb;
  target_image public.entry_images%rowtype;
  target_image_id bigint;
  existing_image_count integer;
  replacement_count integer := 0;
  addition_count integer := 0;
  original_count integer := 0;
  state_count integer := 0;
  visible_image_count integer := 0;
  processed_image_ids bigint[] := array[]::bigint[];
  processed_state_image_ids bigint[] := array[]::bigint[];
  current_display_position smallint;
  current_is_hidden boolean;
begin
  if jsonb_typeof(replacements) <> 'array'
     or jsonb_typeof(additions) <> 'array'
     or jsonb_typeof(image_states) <> 'array'
     or jsonb_array_length(replacements) > 5
     or jsonb_array_length(additions) > 5
     or jsonb_array_length(image_states) > 100
     or (
       jsonb_array_length(replacements) = 0
       and jsonb_array_length(additions) = 0
       and jsonb_array_length(image_states) = 0
       and new_original_storage_path is null
     ) then
    raise exception 'invalid_media_corrections';
  end if;

  select *
  into grant_row
  from public.submission_edit_grants
  where id = target_grant_id
    and entry_id = target_entry_id
    and grantee_profile_id = target_grantee_profile_id
    and is_active = true
    and revoked_at is null
    and expires_at > now()
  for update;

  if not found then
    raise exception 'correction_grant_unavailable';
  end if;

  perform 1
  from public.entries
  where id = target_entry_id
    and owner_id = target_grantee_profile_id
    and withdrawn_at is null
  for update;

  if not found then
    raise exception 'entry_unavailable';
  end if;

  select count(*)
  into existing_image_count
  from public.entry_images
  where entry_id = target_entry_id;

  if jsonb_array_length(additions) > 0 and not grant_row.allow_add_images then
    raise exception 'image_addition_not_allowed';
  end if;

  if new_original_storage_path is not null and not grant_row.allow_replace_original then
    raise exception 'original_replacement_not_allowed';
  end if;

  for replacement in select value from jsonb_array_elements(replacements)
  loop
    target_image_id := (replacement->>'image_id')::bigint;
    if target_image_id = any(processed_image_ids) then
      raise exception 'duplicate_image';
    end if;

    select *
    into target_image
    from public.entry_images
    where id = target_image_id
      and entry_id = target_entry_id
    for update;

    if not found or not (
      target_image_id = any(grant_row.allowed_image_ids)
      or target_image.position = any(grant_row.allowed_positions)
    ) then
      raise exception 'image_not_allowed';
    end if;

    update public.entry_image_revisions
    set is_active = false,
        superseded_at = now()
    where image_id = target_image_id
      and is_active = true;

    insert into public.entry_image_revisions (
      entry_id, image_id, grant_id, storage_object_path,
      display_storage_path, crop_x, crop_y, zoom, rotation,
      aspect_ratio, created_by
    ) values (
      target_entry_id,
      target_image_id,
      target_grant_id,
      replacement->>'storage_object_path',
      replacement->>'display_storage_path',
      (replacement->>'crop_x')::double precision,
      (replacement->>'crop_y')::double precision,
      (replacement->>'zoom')::double precision,
      (replacement->>'rotation')::double precision,
      '4/3',
      target_grantee_profile_id
    );

    processed_image_ids := array_append(processed_image_ids, target_image_id);
    replacement_count := replacement_count + 1;
  end loop;

  for addition in select value from jsonb_array_elements(additions)
  loop
    addition_count := addition_count + 1;
    insert into public.entry_images (
      entry_id, storage_path, position, crop_x, crop_y, zoom,
      rotation, aspect_ratio
    ) values (
      target_entry_id,
      addition->>'display_storage_path',
      existing_image_count + addition_count,
      (addition->>'crop_x')::double precision,
      (addition->>'crop_y')::double precision,
      (addition->>'zoom')::double precision,
      (addition->>'rotation')::double precision,
      '4/3'
    );
  end loop;

  for image_state in select value from jsonb_array_elements(image_states)
  loop
    target_image_id := (image_state->>'image_id')::bigint;
    if target_image_id = any(processed_state_image_ids) then
      raise exception 'duplicate_image_state';
    end if;

    select *
    into target_image
    from public.entry_images
    where id = target_image_id
      and entry_id = target_entry_id
    for update;

    if not found
       or (image_state->>'display_position')::integer not between 1 and 999 then
      raise exception 'invalid_image_state';
    end if;

    select
      coalesce(setting.display_position, target_image.position)::smallint,
      coalesce(setting.is_hidden, false)
    into current_display_position, current_is_hidden
    from (select 1) seed
    left join public.entry_image_display_settings setting
      on setting.image_id = target_image_id;

    if (image_state->>'is_hidden')::boolean <> current_is_hidden
       and not grant_row.allow_remove_images then
      raise exception 'image_removal_not_allowed';
    end if;

    if (image_state->>'display_position')::smallint <> current_display_position
       and not grant_row.allow_reorder_images then
      raise exception 'image_reorder_not_allowed';
    end if;

    insert into public.entry_image_display_settings (
      image_id, entry_id, display_position, is_hidden,
      grant_id, updated_by, updated_at
    ) values (
      target_image_id,
      target_entry_id,
      (image_state->>'display_position')::smallint,
      (image_state->>'is_hidden')::boolean,
      target_grant_id,
      target_grantee_profile_id,
      now()
    )
    on conflict (image_id) do update set
      display_position = excluded.display_position,
      is_hidden = excluded.is_hidden,
      grant_id = excluded.grant_id,
      updated_by = excluded.updated_by,
      updated_at = excluded.updated_at;

    processed_state_image_ids := array_append(processed_state_image_ids, target_image_id);
    state_count := state_count + 1;
  end loop;

  select count(*)
  into visible_image_count
  from public.entry_images image_row
  left join public.entry_image_display_settings setting
    on setting.image_id = image_row.id
  where image_row.entry_id = target_entry_id
    and coalesce(setting.is_hidden, false) = false;

  if visible_image_count < 1 or visible_image_count > 5 then
    raise exception 'invalid_visible_image_count';
  end if;

  if new_original_storage_path is not null then
    update public.entry_original_image_revisions
    set is_active = false,
        superseded_at = now()
    where entry_id = target_entry_id
      and is_active = true;

    insert into public.entry_original_image_revisions (
      entry_id, grant_id, storage_object_path, created_by
    ) values (
      target_entry_id,
      target_grant_id,
      new_original_storage_path,
      target_grantee_profile_id
    );
    original_count := 1;
  end if;

  update public.submission_edit_grants
  set updated_at = now()
  where id = target_grant_id;

  return jsonb_build_object(
    'replacements', replacement_count,
    'additions', addition_count,
    'image_states', state_count,
    'originals', original_count
  );
end;
$$;

revoke all on function public.apply_submission_media_corrections(bigint, uuid, uuid, jsonb, jsonb, jsonb, text) from public;
revoke all on function public.apply_submission_media_corrections(bigint, uuid, uuid, jsonb, jsonb, jsonb, text) from anon;
revoke all on function public.apply_submission_media_corrections(bigint, uuid, uuid, jsonb, jsonb, jsonb, text) from authenticated;
grant execute on function public.apply_submission_media_corrections(bigint, uuid, uuid, jsonb, jsonb, jsonb, text) to service_role;

commit;
