-- Adds narrowly scoped, time-limited photo correction grants.
-- Existing entries, votes, entry_images, image order, and Storage objects are
-- not rewritten by this migration. Replacement photos are stored as append-only
-- revisions and the original entry_images row remains the permanent baseline.
begin;

create table if not exists public.submission_edit_grants (
  id uuid primary key default gen_random_uuid(),
  entry_id bigint references public.entries(id) on delete set null,
  grantee_profile_id uuid not null references public.profiles(id) on delete restrict,
  allowed_positions smallint[] not null default array[1, 2, 3, 4, 5]::smallint[],
  reason text,
  expires_at timestamptz not null,
  is_active boolean not null default true,
  granted_by uuid references public.profiles(id) on delete set null,
  revoked_at timestamptz,
  revoked_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint submission_edit_grants_positions_check check (
    cardinality(allowed_positions) between 1 and 5
    and allowed_positions <@ array[1, 2, 3, 4, 5]::smallint[]
  ),
  constraint submission_edit_grants_expiry_check check (expires_at > created_at)
);

create unique index if not exists submission_edit_grants_one_active_per_entry_idx
  on public.submission_edit_grants(entry_id)
  where is_active = true;

create index if not exists submission_edit_grants_entry_idx
  on public.submission_edit_grants(entry_id);

create index if not exists submission_edit_grants_grantee_idx
  on public.submission_edit_grants(grantee_profile_id);

create index if not exists submission_edit_grants_grantee_active_idx
  on public.submission_edit_grants(grantee_profile_id, expires_at)
  where is_active = true;

create index if not exists submission_edit_grants_granted_by_idx
  on public.submission_edit_grants(granted_by)
  where granted_by is not null;

create index if not exists submission_edit_grants_revoked_by_idx
  on public.submission_edit_grants(revoked_by)
  where revoked_by is not null;

create table if not exists public.entry_image_revisions (
  id bigint generated by default as identity primary key,
  entry_id bigint references public.entries(id) on delete set null,
  image_id bigint references public.entry_images(id) on delete set null,
  grant_id uuid references public.submission_edit_grants(id) on delete set null,
  storage_object_path text not null,
  display_storage_path text not null,
  crop_x double precision not null default 0,
  crop_y double precision not null default 0,
  zoom double precision not null default 1,
  rotation double precision not null default 0,
  aspect_ratio text not null default '4/3',
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  superseded_at timestamptz,
  constraint entry_image_revisions_crop_x_check check (crop_x between -50 and 50),
  constraint entry_image_revisions_crop_y_check check (crop_y between -50 and 50),
  constraint entry_image_revisions_zoom_check check (zoom between 1 and 3),
  constraint entry_image_revisions_rotation_check check (rotation between -180 and 180),
  constraint entry_image_revisions_aspect_ratio_check check (aspect_ratio = '4/3')
);

create unique index if not exists entry_image_revisions_one_active_per_image_idx
  on public.entry_image_revisions(image_id)
  where is_active = true;

create index if not exists entry_image_revisions_entry_created_idx
  on public.entry_image_revisions(entry_id, created_at desc);

create index if not exists entry_image_revisions_image_idx
  on public.entry_image_revisions(image_id);

create index if not exists entry_image_revisions_grant_idx
  on public.entry_image_revisions(grant_id)
  where grant_id is not null;

create index if not exists entry_image_revisions_created_by_idx
  on public.entry_image_revisions(created_by)
  where created_by is not null;

alter table public.submission_edit_grants enable row level security;
alter table public.entry_image_revisions enable row level security;

revoke all on table public.submission_edit_grants from anon, authenticated;
revoke all on table public.entry_image_revisions from anon, authenticated;
grant select on table public.submission_edit_grants to authenticated;
grant all on table public.submission_edit_grants to service_role;
grant all on table public.entry_image_revisions to service_role;
grant usage, select on sequence public.entry_image_revisions_id_seq to service_role;

drop policy if exists "players read own correction grants" on public.submission_edit_grants;
create policy "players read own correction grants"
on public.submission_edit_grants
for select
to authenticated
using (grantee_profile_id = (select auth.uid()));

-- A correction grant only opens INSERT access to a new, uniquely named object
-- inside the signed-in player's own folder. Linking that object to an entry is
-- still performed by the server route after checking the exact grant, entry,
-- owner, image position, expiry, and file existence.
drop policy if exists "authorized correction entry uploads" on storage.objects;
create policy "authorized correction entry uploads"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'cos-entries'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and lower(storage.extension(name)) = any (array['jpg', 'jpeg', 'png', 'webp'])
  and storage.filename(name) like '%-correction-entry-%'
  and exists (
    select 1
    from public.submission_edit_grants grant_row
    join public.entries entry_row on entry_row.id = grant_row.entry_id
    where grant_row.grantee_profile_id = (select auth.uid())
      and entry_row.owner_id = (select auth.uid())
      and grant_row.is_active = true
      and grant_row.revoked_at is null
      and grant_row.expires_at > now()
  )
);

-- Atomic append-only activation of new image revisions. This function is not
-- callable by browser roles; the server validates the authenticated player and
-- uploaded Storage objects before invoking it with service_role.
create or replace function public.apply_submission_image_corrections(
  target_entry_id bigint,
  target_grantee_profile_id uuid,
  target_grant_id uuid,
  replacements jsonb
)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  grant_row public.submission_edit_grants%rowtype;
  replacement jsonb;
  target_image public.entry_images%rowtype;
  target_image_id bigint;
  processed integer := 0;
  processed_image_ids bigint[] := array[]::bigint[];
begin
  if jsonb_typeof(replacements) <> 'array'
     or jsonb_array_length(replacements) < 1
     or jsonb_array_length(replacements) > 5 then
    raise exception 'invalid_replacements';
  end if;

  select *
  into grant_row
  from public.submission_edit_grants
  where id = target_grant_id
    and entry_id = target_entry_id
    and grantee_profile_id = target_grantee_profile_id
    and is_active = true
    and revoked_at is null
    and expires_at > now()
  for update;

  if not found then
    raise exception 'correction_grant_unavailable';
  end if;

  for replacement in select value from jsonb_array_elements(replacements)
  loop
    target_image_id := (replacement->>'image_id')::bigint;
    if target_image_id = any(processed_image_ids) then
      raise exception 'duplicate_image';
    end if;

    select *
    into target_image
    from public.entry_images
    where id = target_image_id
      and entry_id = target_entry_id
    for update;

    if not found or not (target_image.position = any(grant_row.allowed_positions)) then
      raise exception 'image_not_allowed';
    end if;

    update public.entry_image_revisions
    set is_active = false,
        superseded_at = now()
    where image_id = target_image_id
      and is_active = true;

    insert into public.entry_image_revisions (
      entry_id,
      image_id,
      grant_id,
      storage_object_path,
      display_storage_path,
      crop_x,
      crop_y,
      zoom,
      rotation,
      aspect_ratio,
      created_by
    ) values (
      target_entry_id,
      target_image_id,
      target_grant_id,
      replacement->>'storage_object_path',
      replacement->>'display_storage_path',
      (replacement->>'crop_x')::double precision,
      (replacement->>'crop_y')::double precision,
      (replacement->>'zoom')::double precision,
      (replacement->>'rotation')::double precision,
      '4/3',
      target_grantee_profile_id
    );

    processed_image_ids := array_append(processed_image_ids, target_image_id);
    processed := processed + 1;
  end loop;

  update public.submission_edit_grants
  set updated_at = now()
  where id = target_grant_id;

  return processed;
end;
$$;

revoke all on function public.apply_submission_image_corrections(bigint, uuid, uuid, jsonb) from public;
revoke all on function public.apply_submission_image_corrections(bigint, uuid, uuid, jsonb) from anon;
revoke all on function public.apply_submission_image_corrections(bigint, uuid, uuid, jsonb) from authenticated;
grant execute on function public.apply_submission_image_corrections(bigint, uuid, uuid, jsonb) to service_role;

commit;
